### ISSUE TITLE
Tutorial on how to use this translator & how to generate LLVM bitcode for firmware source code mixed with assembly code and staticallly linked binary of ARM32

### ISSUE THREAD

**Issue by yikuoyansui** [Inception-framework/translator#1]
Really helpful work! I am working on a project which needs to compile firmware souce code mixed with assembly code and statically linked binary into LLVM bitcode using Clang. For now, I have already successfully compiled the same firmware into elf using arm-gcc. The errors "instantiated into assembly here" happen when I try to compile the firmware source code using Clang. With that being said, I am wondering how you handled such a compiling issue and successfully compiled the  firmware C/C++ source code into LLVM bitcode and merged them with lifted ARM assembly code and statically linked binary. Any kind of help or guidance are appreciated!

**Comment by giocamurati** [comment]
Hello @yikuoyansui, thank you for your feedback!

Here are two pointers that should answer your question in detail:

1. For a practical guide on how to use our tool, we suggest you to follow this tutorial
https://github.com/Inception-framework/tutorial
In particular, the "step by step" example should address your case https://github.com/Inception-framework/tutorial#Step
It is a minimal dummy example which shows all the necessary steps (compiling with Clang, compiling with gcc, lifting and merging with our tool). The resulting code can then run in our (slightly modified) version of Klee https://github.com/Inception-framework/analyzer.
As of now we support Arm-v7-M.

1. For a detailed description of our approach and tool some useful resources are our paper
https://www.usenix.org/system/files/conference/usenixsecurity18/sec18-corteggiani.pdf
(in particular sections 2 and 3) 
and the slides of the presentation https://www.usenix.org/sites/default/files/conference/protected-files/security18_slides_corteggiani.pdf (in particular slides 52-62).

Do not hesitate to come back to us if you need any help with the code or if you want to discuss some aspect of our approach.

Giovanni
